### ISSUE TITLE
roll_camera function not defined

### ISSUE THREAD

**Issue by lewisr20** [Extraltodeus/3D_wireframe_engine#1]
camera = roll_camera(camera,0)

According to the machine the roll_camera function not defined. I might guess a valid combination but should this function be defined or is it a spelling issue?

**Comment by Extraltodeus** [comment]
Nah chatGPT never came with a working function and while I remember figuring this out a few years ago, I can't figure it out today. The roll_camera function is not working neither.

I close the issue because I don't intend to make it a full fledged scalable 3D engine, it is good as it is :)

Thank you for caring tho!

**Comment by Extraltodeus** [comment]
I removed the key binding tho :p
